name: PR Workflow

on:
  pull_request:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci --registry=https://registry.npmjs.org/
      - name: Lint
        run: npm run lint
      - name: Format
        run: npm run format
